[package]
name = "rust_aoc_2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
phf = {version = "0.10", features = ["macros"]}
lazy_static = "1.4.0"
common_macros = "0.1.1"